### ISSUE TITLE
Padding on FE Search

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#169] opened 2024-05-22 10:59 UTC
**Describe the bug**
Searching for something in the FE searchbar messes up some padding

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dancingsushii** [comment] 2024-06-03 16:01
Closed as duplicate of [#168](https://github.com/amosproj/amos2024ss04-building-information-enhancer/issues/168).

**Closed by dancingsushii** 2024-06-03 16:01 UTC
Labels: bug, frontend
