### ISSUE TITLE
Queryable max zoom level for individual datasets

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#271] opened 2024-06-12 07:55 UTC
**Describe the bug**
Show zoom level label if it is necessary for a dataset

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lucas-Nan** [comment] 2024-06-18 10:11
this very much depends on the performance but of course it can already be added

**Comment by Corgam** [comment] 2024-06-25 13:01
Duplicate of [#318](https://github.com/amosproj/amos2024ss04-building-information-enhancer/issues/318)

**Closed by Corgam** 2024-06-25 13:01 UTC
Labels: bug, feature, backend
